services:
  - type: worker
    name: tg-file-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: tgfilebot
      - key: CHANNEL_ID
        sync: false
      - key: OWNER_ID
        sync: false
